#!/usr/bin/env node
/**
 * Refreshes live GitHub stats (stars/forks/pushed_at) into
 * src/data/stats.generated.json — a merge overlay consumed by src/lib/data.ts.
 *
 * Usage:  GITHUB_TOKEN=ghp_xxx npm run refresh-stats
 * Notes:
 *  - Unauthenticated GitHub API = 60 req/h; authenticated = 5,000 req/h.
 *    A token is REQUIRED for the full catalog.
 *  - Conditional requests via cached ETags make repeat runs cheap (304s).
 */

import { writeFile, readFile, mkdir, readdirSync, readFileSync } from 'node:fs/promises'
import { existsSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const OUT = join(ROOT, 'src', 'data', 'stats.generated.json')
const CACHE = join(ROOT, 'scripts', '.stats-cache.json')
const BATCH = 60

const token = process.env.GITHUB_TOKEN
if (!token) {
  console.error('✖ GITHUB_TOKEN is required (unauthenticated quota is 60/h).')
  console.error('  Create a read-only classic token at https://github.com/settings/tokens')
  process.exit(1)
}

/** Pull every repo id out of the dataset files without importing TS. */
function collectIds() {
  const dir = join(ROOT, 'src', 'data', 'repos')
  const ids = []
  for (const f of readdirSync(dir)) {
    if (!f.endsWith('.ts') || f === 'factory.ts' || f === 'types.ts') continue
    const src = readFileSync(join(dir, f), 'utf8')
    for (const m of src.matchAll(/seed\(\s*'([^']+?)'/g)) ids.push(m[1])
  }
  return [...new Set(ids)]
}

async function fetchRepo(id, etag) {
  const headers = {
    Authorization: `Bearer ${token}`,
    Accept: 'application/vnd.github+json',
    'X-GitHub-Api-Version': '2022-11-28',
  }
  if (etag) headers['If-None-Match'] = etag
  const res = await fetch(`https://api.github.com/repos/${id}`, { headers })
  if (res.status === 304) return { notModified: true }
  if (res.status === 404) return { missing: true }
  if (!res.ok) throw new Error(`${id}: HTTP ${res.status}`)
  const j = await res.json()
  return {
    etag: res.headers.get('etag'),
    stars: j.stargazers_count,
    forks: j.forks_count,
    updated: typeof j.pushed_at === 'string' ? j.pushed_at.slice(0, 7) : undefined,
  }
}

async function main() {
  const ids = collectIds()
  console.log(`• ${ids.length} repositories in catalog`)

  let cache = {}
  try {
    cache = JSON.parse(await readFile(CACHE, 'utf8'))
  } catch {}

  const overlay = {}
  let done = 0
  let fresh304 = 0
  let missing404 = 0
  let failed = 0

  for (let i = 0; i < ids.length; i += BATCH) {
    const batch = ids.slice(i, i + BATCH)
    const results = await Promise.allSettled(batch.map((id) => fetchRepo(id, cache[id]?.etag)))
    results.forEach((r, k) => {
      const id = batch[k]
      if (r.status !== 'fulfilled') {
        failed++
        console.warn(`  ⚠ ${r.reason?.message ?? r.reason}`)
        return
      }
      const v = r.value
      if (v.notModified && cache[id]?.data) {
        fresh304++
        overlay[id] = cache[id].data
      } else if (v.missing) {
        missing404++
        console.warn(`  ⚠ 404 ${id}`)
      } else if (v.stars !== undefined) {
        overlay[id] = { stars: v.stars, forks: v.forks, updated: v.updated }
        cache[id] = { etag: v.etag, data: overlay[id] }
      }
    })
    done += batch.length
    console.log(`  ${done}/${ids.length}`)
    if (i + BATCH < ids.length) await new Promise((s) => setTimeout(s, 1200))
  }

  await mkdir(dirname(OUT), { recursive: true })
  await writeFile(
    OUT,
    `${JSON.stringify(
      { _comment: 'generated by scripts/fetch-stats.mjs — do not edit', fetchedAt: new Date().toISOString(), entries: overlay },
      null,
      2,
    )}\n`,
  )
  if (!existsSync(CACHE) || fresh304 > 0 || Object.keys(overlay).length > 0) {
    await writeFile(CACHE, JSON.stringify(cache)).catch(() => {})
  }
  console.log(`✔ wrote ${Object.keys(overlay).length} entries → src/data/stats.generated.json`)
  console.log(`  fresh:${ids.length - failed - missing404} · via-304:${fresh304} · missing:${missing404} · errors:${failed}`)
}

main().catch((e) => {
  console.error('✖ refresh failed:', e.message)
  process.exit(1)
})
